spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-34-231-63-30.compute-1.amazonaws.com:5432/d4mpft0kpr8fv
    username: kjgaxubixgtogm
    password: 45d1cac5b8854b5ae6661252776eab45e471ed1ee4d1041b82f41b5930dbaa58
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  messages:
    always-use-message-format: true
  data:
    rest:
      default-page-size: 10

springdoc:
  swagger-ui:
    path: swagger-ui
  api-docs:
    path: /api-docs

